/*
 * hello_kern.c: Minimal eBPF program to log execve syscalls.
 *
 * This program attaches to the 'sys_enter_execve' tracepoint
 * and prints a simple "Hello eBPF!" message to the kernel trace pipe
 * every time an execve() syscall is executed.
 */

/*
 * vmlinux.h: This header is generated by 'bpftool gen vmlinux'
 * and contains all kernel type definitions. It is required to access
 * tracepoint context structures (e.g., struct trace_event_raw_sys_enter).
 */
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

/*
 * The SEC("...") macro defines the section name for the eBPF program.
 * The loader (libbpf) uses this to determine:
 * 1. The program type (tracepoint)
 * 2. The event to attach to (syscalls/sys_enter_execve)
 */
SEC("tracepoint/syscalls/sys_enter_execve")
int handle_execve_enter(struct trace_event_raw_sys_enter* ctx)
{
    /*
     * bpf_printk:
     * A simple helper macro (from bpf_helpers.h) to print messages
     * to the kernel trace pipe.
     *
     * You can read this output in the CLion terminal with:
     * sudo cat /sys/kernel/debug/tracing/trace_pipe
     */
    bpf_printk("Hello eBPF! execve syscall detected.\n");

    /*
     * All eBPF programs must return an integer.
     * For tracepoints, 0 indicates success.
     */
    return 0;
}

/*
 * Mandatory license for eBPF programs.
 * The kernel will refuse to load the program without a GPL-compatible license.
 */
char LICENSE[] SEC("license") = "GPL";